/* eslint-disable prettier/prettier */
export const COLUMNS = {
  userId: '会員ID',
  term: '期',
  userLastName: '会員姓',
  userFirstName: '会員名',
  userLastNameKana: '会員姓カナ',
  userFirstNameKana: '会員名カナ',
  universityId: '所属ID',
  universityOther: '所属その他',
  positionId: '役職ID',
  mailAddress: 'メールアドレス',
  createDate: '作成日時',
  updateDate: '更新日時',
  userName: '会員姓名',
  userNameKana: '会員姓名カナ',
  equipmentCategoryId: '装備カテゴリID',
  equipmentCategoryName1: '装備カテゴリ名1',
  equipmentCategoryName2: '装備カテゴリ名2',
  universityName: '大学名',
  isReturnPlace: '返却場所フラグ',
  positionName: '役職名',
  isManager: '管理者権限',

};
