/* eslint-disable prettier/prettier */
export const PARAMS = {
  userId: '会員ID',
  term: '期',
  userLastName: '会員姓',
  userFirstName: '会員名',
  userLastNameKana: '会員姓カナ',
  userFirstNameKana: '会員名カナ',
  universityId: '所属ID',
  universityOther: '所属その他',
  positionId: '役職ID',
  mailAddress: 'メールアドレス',
  createDate: '作成日時',
  updateDate: '更新日時',
  userName: '会員姓名',
  userNameKana: '会員姓名カナ',
  equipmentCategoryId: '装備カテゴリID',
  equipmentCategoryName1: '装備カテゴリ名1',
  equipmentCategoryName2: '装備カテゴリ名2',
  universityName: '大学名',
  isReturnPlace: '返却場所フラグ',
  positionName: '役職名',
  isManager: '管理者権限',
  equipmentId: '装備ID',
  purchaseDateFrom:'購入日(From)',
  purchaseDateTo:'購入日(To)',
  statusCd: '状態区分',
  lendingId: '持出ID',
  lendUserId: '持出会員ID',
  returnUserId: '返却会員ID',
  lendUserNameKana: '持出会員姓名カナ',
  returnUserNameKana: '返却会員姓名カナ',
  lendDate:'持出日', 
  lendFrom: '持出日(From)',
  lendTo: '持出日(To)',
  useFrom: '使用期間(From)',
  useTo: '使用期間(To)',
  destination: '行き先',
  returnDate:'返却日',
  isReturn: '返却済フラグ',
  returnPlaceId: '返却場所ID',
  returnPlaceOther: '返却場所その他',
  remark: '備考',
  isHandOver: '直接受け渡しフラグ',
};
